### ISSUE TITLE
Remove DOM element instead of hiding it

### ISSUE THREAD

**Issue by roszpun** [reinerBa/Vue-Responsive#13]
Hello, I'm developing an app, which has mobile and desktop views. Ideally, I would like to display some components conditionally depending on the breakpoints. Currently directive only applies `display: none;`. Is it possible to remove the DOM element instead?

**Comment by reinerBa** [comment]
Hello, removing is in vue a different thing than hiding. 
You can hide with "v-show" and remove with "v-if", with this directive the last is not possible. Because it works in the DOM elements itself.
Other Plugins exists with give you a property that indicates the current display size, you can use this to do something like v-if="big" or v-if="!big".
